public enum UpgradeType
{
    POWER_UP = 1,
    INCREASE_PROJECTILE_SPEED,
    MULTI_SHOT_SAME_DIRECTION,
    MULTI_SHOT_RANDOM_DIRECTION,
    SHOOT_PROJECTILE_FROM_BEHIND,
    DECREASE_PROJECTILE_RELOAD_TIME,
    INCREASE_ROTATION_SPEED,
    NORMALIZE_RANDOM_SHOT_DIRECTION,
    HEAL_HP_PER_SECOND,
    HEAL_HP_ON_KILL,
    INCREASE_HEALING_EFFECTIVENESS,
    INCREASE_MAX_HP,
    DECREASE_ENEMY_SPAWN_INTERVAL,
    INCREASE_ENEMY_PER_WAVE,
    MULTIPLY_ENEMY_COUNT,
}